// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package dbgen

import (
	"context"
)

const insertPageView = `-- name: InsertPageView :exec
INSERT INTO page_views (path, product_id, referrer, user_agent, visitor_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertPageViewParams struct {
	Path      string `json:"path"`
	ProductID *int64 `json:"product_id"`
	Referrer  string `json:"referrer"`
	UserAgent string `json:"user_agent"`
	VisitorID string `json:"visitor_id"`
}

func (q *Queries) InsertPageView(ctx context.Context, arg InsertPageViewParams) error {
	_, err := q.db.ExecContext(ctx, insertPageView,
		arg.Path,
		arg.ProductID,
		arg.Referrer,
		arg.UserAgent,
		arg.VisitorID,
	)
	return err
}

const insertWAClick = `-- name: InsertWAClick :exec
INSERT INTO wa_clicks (product_id, click_type) VALUES (?, ?)
`

type InsertWAClickParams struct {
	ProductID *int64 `json:"product_id"`
	ClickType string `json:"click_type"`
}

func (q *Queries) InsertWAClick(ctx context.Context, arg InsertWAClickParams) error {
	_, err := q.db.ExecContext(ctx, insertWAClick, arg.ProductID, arg.ClickType)
	return err
}

const todayViews = `-- name: TodayViews :one
SELECT COUNT(*) as total FROM page_views WHERE DATE(created_at) = DATE('now')
`

func (q *Queries) TodayViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, todayViews)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const todayWAClicks = `-- name: TodayWAClicks :one
SELECT COUNT(*) as total FROM wa_clicks WHERE DATE(created_at) = DATE('now')
`

func (q *Queries) TodayWAClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, todayWAClicks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const topProducts = `-- name: TopProducts :many
SELECT p.id, p.title, p.image_url, COUNT(pv.id) as views
FROM page_views pv
JOIN products p ON p.id = pv.product_id
WHERE pv.product_id IS NOT NULL AND pv.created_at >= datetime('now', '-30 days')
GROUP BY p.id
ORDER BY views DESC
LIMIT 10
`

type TopProductsRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	ImageUrl string `json:"image_url"`
	Views    int64  `json:"views"`
}

func (q *Queries) TopProducts(ctx context.Context) ([]TopProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, topProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopProductsRow{}
	for rows.Next() {
		var i TopProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalViews = `-- name: TotalViews :one
SELECT COUNT(*) as total FROM page_views
`

func (q *Queries) TotalViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalViews)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const totalWAClicks = `-- name: TotalWAClicks :one
SELECT COUNT(*) as total FROM wa_clicks
`

func (q *Queries) TotalWAClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalWAClicks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const uniqueVisitors = `-- name: UniqueVisitors :one
SELECT COUNT(DISTINCT visitor_id) as total FROM page_views WHERE visitor_id != ''
`

func (q *Queries) UniqueVisitors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, uniqueVisitors)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const viewsPerDay = `-- name: ViewsPerDay :many
SELECT DATE(created_at) as day, COUNT(*) as views
FROM page_views
WHERE created_at >= datetime('now', '-30 days')
GROUP BY DATE(created_at)
ORDER BY day
`

type ViewsPerDayRow struct {
	Day   interface{} `json:"day"`
	Views int64       `json:"views"`
}

func (q *Queries) ViewsPerDay(ctx context.Context) ([]ViewsPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, viewsPerDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewsPerDayRow{}
	for rows.Next() {
		var i ViewsPerDayRow
		if err := rows.Scan(&i.Day, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wAClicksByType = `-- name: WAClicksByType :many
SELECT click_type, COUNT(*) as clicks
FROM wa_clicks
GROUP BY click_type
`

type WAClicksByTypeRow struct {
	ClickType string `json:"click_type"`
	Clicks    int64  `json:"clicks"`
}

func (q *Queries) WAClicksByType(ctx context.Context) ([]WAClicksByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, wAClicksByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WAClicksByTypeRow{}
	for rows.Next() {
		var i WAClicksByTypeRow
		if err := rows.Scan(&i.ClickType, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
