// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Product struct {
	ID            int64     `json:"id"`
	Url           string    `json:"url"`
	Platform      string    `json:"platform"`
	Title         string    `json:"title"`
	Price         string    `json:"price"`
	OriginalPrice string    `json:"original_price"`
	ImageUrl      string    `json:"image_url"`
	Description   string    `json:"description"`
	Rating        string    `json:"rating"`
	AddedAt       time.Time `json:"added_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
