// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type PageView struct {
	ID        int64     `json:"id"`
	Path      string    `json:"path"`
	ProductID *int64    `json:"product_id"`
	Referrer  string    `json:"referrer"`
	UserAgent string    `json:"user_agent"`
	VisitorID string    `json:"visitor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID              int64     `json:"id"`
	Url             string    `json:"url"`
	Platform        string    `json:"platform"`
	Title           string    `json:"title"`
	Price           string    `json:"price"`
	OriginalPrice   string    `json:"original_price"`
	ImageUrl        string    `json:"image_url"`
	Description     string    `json:"description"`
	Rating          string    `json:"rating"`
	AddedAt         time.Time `json:"added_at"`
	Category        string    `json:"category"`
	Images          string    `json:"images"`
	LongDescription string    `json:"long_description"`
	IsNew           int64     `json:"is_new"`
	IsBestseller    int64     `json:"is_bestseller"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type WaClick struct {
	ID        int64     `json:"id"`
	ProductID *int64    `json:"product_id"`
	ClickType string    `json:"click_type"`
	CreatedAt time.Time `json:"created_at"`
}
