// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
)

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, url, platform, title, price, original_price, image_url, description, rating, added_at, category FROM products WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Platform,
		&i.Title,
		&i.Price,
		&i.OriginalPrice,
		&i.ImageUrl,
		&i.Description,
		&i.Rating,
		&i.AddedAt,
		&i.Category,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (url, platform, title, price, original_price, image_url, description, rating, category)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, url, platform, title, price, original_price, image_url, description, rating, added_at, category
`

type InsertProductParams struct {
	Url           string `json:"url"`
	Platform      string `json:"platform"`
	Title         string `json:"title"`
	Price         string `json:"price"`
	OriginalPrice string `json:"original_price"`
	ImageUrl      string `json:"image_url"`
	Description   string `json:"description"`
	Rating        string `json:"rating"`
	Category      string `json:"category"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Url,
		arg.Platform,
		arg.Title,
		arg.Price,
		arg.OriginalPrice,
		arg.ImageUrl,
		arg.Description,
		arg.Rating,
		arg.Category,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Platform,
		&i.Title,
		&i.Price,
		&i.OriginalPrice,
		&i.ImageUrl,
		&i.Description,
		&i.Rating,
		&i.AddedAt,
		&i.Category,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT DISTINCT category FROM products WHERE category != '' ORDER BY category
`

func (q *Queries) ListCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, url, platform, title, price, original_price, image_url, description, rating, added_at, category FROM products ORDER BY added_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Platform,
			&i.Title,
			&i.Price,
			&i.OriginalPrice,
			&i.ImageUrl,
			&i.Description,
			&i.Rating,
			&i.AddedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE products SET category = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Category string `json:"category"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Category, arg.ID)
	return err
}
