// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
)

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, url, platform, title, price, original_price, image_url, description, rating, added_at FROM products WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Platform,
		&i.Title,
		&i.Price,
		&i.OriginalPrice,
		&i.ImageUrl,
		&i.Description,
		&i.Rating,
		&i.AddedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (url, platform, title, price, original_price, image_url, description, rating)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, url, platform, title, price, original_price, image_url, description, rating, added_at
`

type InsertProductParams struct {
	Url           string `json:"url"`
	Platform      string `json:"platform"`
	Title         string `json:"title"`
	Price         string `json:"price"`
	OriginalPrice string `json:"original_price"`
	ImageUrl      string `json:"image_url"`
	Description   string `json:"description"`
	Rating        string `json:"rating"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Url,
		arg.Platform,
		arg.Title,
		arg.Price,
		arg.OriginalPrice,
		arg.ImageUrl,
		arg.Description,
		arg.Rating,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Platform,
		&i.Title,
		&i.Price,
		&i.OriginalPrice,
		&i.ImageUrl,
		&i.Description,
		&i.Rating,
		&i.AddedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, url, platform, title, price, original_price, image_url, description, rating, added_at FROM products ORDER BY added_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Platform,
			&i.Title,
			&i.Price,
			&i.OriginalPrice,
			&i.ImageUrl,
			&i.Description,
			&i.Rating,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
